import gradio as gr
from docx import Document
from docx.oxml.ns import qn
from docx.shared import Pt
from pathlib import Path
from datetime import datetime

from crew.create_crew import create_teaching_crew


# ---------------------------------------------------------
# Output directory
# ---------------------------------------------------------

OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)


# ---------------------------------------------------------
# Generate DOCX
# ---------------------------------------------------------

def add_diagram_line(document, text: str):
    """
    Adds one line of a text flow diagram, keeping leading and repeated
    spaces so the ASCII layout is not collapsed by Word.
    """

    paragraph = document.add_paragraph()

    paragraph.paragraph_format.space_before = Pt(0)
    paragraph.paragraph_format.space_after = Pt(0)

    run = paragraph.add_run(text)
    run.font.name = "Consolas"
    run.font.size = Pt(9)

    # Word trims whitespace unless the text node opts out
    text_element = run._element.find(qn("w:t"))

    if text_element is not None:
        text_element.set(qn("xml:space"), "preserve")


def create_docx(topic: str, content: str):
    """
    Creates a DOCX file containing the final teaching output.
    """

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    safe_topic = "".join(
        c if c.isalnum() or c in (" ", "_", "-") else "_"
        for c in topic
    ).strip()

    filename = f"{safe_topic}_{timestamp}.docx"

    file_path = OUTPUT_DIR / filename

    document = Document()

    # Title
    document.add_heading(topic, level=0)

    document.add_paragraph(
        "Generated by AI Teaching Crew"
    )

    document.add_paragraph(
        f"Generated on: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}"
    )

    document.add_paragraph("")

    # Main content
    document.add_heading("Learning Content", level=1)

    # Split output into lines
    lines = content.split("\n")

    in_diagram = False

    for line in lines:

        # Fenced blocks carry the ASCII flow diagram, so their spacing
        # must pass through untouched
        if line.strip().startswith("```"):
            in_diagram = not in_diagram
            continue

        if in_diagram:
            add_diagram_line(document, line)
            continue

        paragraph = line.strip()

        if not paragraph:
            continue

        # Handle markdown-style headings
        if paragraph.startswith("### "):
            document.add_heading(
                paragraph.replace("### ", ""),
                level=3
            )

        elif paragraph.startswith("## "):
            document.add_heading(
                paragraph.replace("## ", ""),
                level=2
            )

        elif paragraph.startswith("# "):
            document.add_heading(
                paragraph.replace("# ", ""),
                level=1
            )

        elif paragraph.startswith("- "):
            document.add_paragraph(
                paragraph[2:],
                style="List Bullet"
            )

        elif paragraph.startswith("* "):
            document.add_paragraph(
                paragraph[2:],
                style="List Bullet"
            )

        else:
            document.add_paragraph(paragraph)

    # Save
    document.save(file_path)

    return str(file_path)


# ---------------------------------------------------------
# Run Crew
# ---------------------------------------------------------

def generate_teaching_content(topic: str):
    """
    Runs the CrewAI teaching pipeline and generates
    both UI output and a DOCX file.
    """

    if not topic or not topic.strip():
        return (
            "Please enter a topic.",
            None
        )

    try:

        # Create Crew
        teaching_crew = create_teaching_crew()

        # Run Crew - the topic entered in the UI is interpolated into
        # every {user_topic} placeholder in task_configuration.yaml
        result = teaching_crew.kickoff(
            inputs={
                "user_topic": topic.strip()
            }
        )

        # Convert CrewAI result to string
        final_output = str(result)

        # Create DOCX
        docx_file = create_docx(
            topic=topic.strip(),
            content=final_output
        )

        return (
            final_output,
            docx_file
        )

    except Exception as e:

        error_message = (
            f"Error while generating teaching content:\n\n"
            f"{type(e).__name__}: {str(e)}"
        )

        return (
            error_message,
            None
        )


# ---------------------------------------------------------
# Gradio UI
# ---------------------------------------------------------

with gr.Blocks(title="AI Teaching Assistant") as demo:

    gr.Markdown(
        """
        # AI Teaching Assistant

        Enter a topic and let the multi-agent CrewAI system
        research, organize, explain, visualize and summarize it.
        """
    )

    with gr.Row():

        topic_input = gr.Textbox(
            label="Topic",
            placeholder="Example: Retrieval Augmented Generation",
            lines=2
        )

    generate_button = gr.Button(
        "Generate Learning Content",
        variant="primary"
    )

    gr.Markdown("## Generated Content")

    output_text = gr.Markdown(
        label="Final Explanation"
    )

    docx_output = gr.File(
        label="Download DOCX",
        type="filepath"
    )

    generate_button.click(
        fn=generate_teaching_content,
        inputs=topic_input,
        outputs=[
            output_text,
            docx_output
        ]
    )


# ---------------------------------------------------------
# Start Application
# ---------------------------------------------------------

if __name__ == "__main__":

    demo.launch()